############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Our Team"
url = "about/"
weight = 2
  
[[main]]
name = "Contact"
url = "contact/"
weight = 3


# footer menu
[[footer]]
name = "Our Team"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3